name: build and test:master


on:
  workflow_call:
      secrets:
            SNYK_TOKEN:
                required: true
 
  pull_request:
    branches: 
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@jmjhox'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:cov
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          
      - name: Deploying image to heroku cloud
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_BACKEND}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
        
  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
    steps:
      - uses: actions/checkout@master
      - name: Use Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm i
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
 
        with:
          command: monitor
        